In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop('species', axis=1)
y = df['species']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=5)

In [ ]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
model_knn.score(X_test, y_test)

0.98

In [ ]:
from sklearn.svm import SVC

In [ ]:
# model_svm = SVC(C = 10, kernel = 'linear', gamma = 'auto')
# we need to remove these for doing grid search cv the scores taken was of these all only
model_svm = SVC(gamma = 'auto')

In [ ]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [ ]:
model_svm.score(X_test, y_test)

1.0

In [ ]:
#for this combo we r getting accuracy of 100% which means the model is overfit
# as we can see by changing values of hyperparameteres we are getting different values of scores to use the most efficient combination of the parameters now let's do grid search CV

# Grid Search CV

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier = GridSearchCV((model_svm), {
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'],
},cv=5, return_train_score=False)
# here we are continously checking the cross validation at 5 to ensure our model will not get overfit i.e., getting accuracy of 100%

In [ ]:
# now for this we do not need to do the train test split we can use the x and y directly
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.00826693, 0.00367622, 0.00417948, 0.00623336, 0.0093637 ,
        0.00691891, 0.0075532 , 0.00752425]),
 'std_fit_time': array([0.00242668, 0.00041048, 0.00108031, 0.00282392, 0.00217015,
        0.00142006, 0.00042652, 0.00093404]),
 'mean_score_time': array([0.0045506 , 0.00278945, 0.00288143, 0.00601478, 0.01020346,
        0.00762043, 0.00571728, 0.00648379]),
 'std_score_time': array([0.00114777, 0.00051027, 0.0002731 , 0.00285242, 0.00593368,
        0.00186012, 0.00116448, 0.00092197]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
results = pd.DataFrame(classifier.cv_results_)
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008267,0.002427,0.004551,0.001148,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.003676,0.000410,0.002789,0.000510,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004179,0.001080,0.002881,0.000273,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.006233,0.002824,0.006015,0.002852,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.009364,0.002170,0.010203,0.005934,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.006919,0.001420,0.007620,0.001860,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.007553,0.000427,0.005717,0.001164,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.007524,0.000934,0.006484,0.000922,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [ ]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

# Random Search CV

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r = RandomizedSearchCV((model_svm), {
    'C' : [1,10,20,30],
    'kernel' : ['rbf','linear'],
},n_iter=4, cv=5, return_train_score=False)

In [ ]:
classifier_r.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
results_r = pd.DataFrame(classifier_r.cv_results_)
results_r

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005928,0.003339,0.003604,0.000768,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.004622,0.000804,0.003678,0.000834,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004286,0.000167,0.003039,0.000090,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.004113,0.000323,0.002919,0.000114,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,4

In [ ]:
results_r[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1        1          rbf         0.980000
2        1       linear         0.980000
3       20       linear         0.966667

In [ ]:
# here it was not necessary to use it because it was just 8 iterations overall we will use it in random forest and XGBoost where iterations will be a lot higher